[package]
name = "weresocool_shared"
version = "0.1.0"
authors = ["xasopheno <danny@xasopheno.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
float-cmp = "0.8.0"
num-rational = "0.2.4"
