[package]
name = "filters"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.6.4"

[dev-dependencies]
probability = "0.15.12"
